name: SecureSDLC

on:
  workflow_dispatch: {}
  pull_request: {}
  workflow_call: {} # needed when being called from other workflow
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: test
        run: |
          pwd



  # securesdlc:
  #   uses: dso-migrateme/securesdlc/.github/workflows/securesdlc.yml@main