name: SecureSDLC

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: test
        run: |
          pwd



  securesdlc:
    uses: dso-migrateme/securesdlc/.github/workflows/securesdlc.yml@main