name: Local

on:
  workflow_dispatch: {}
  pull_request: {}
  # pull_request_target: {} # Gives workflows higher permissions. Not desired when working with public forks.
  push:
    branches:
      - {{ github.event.repository.default_branch }}

jobs:
  local-step:
    runs-on: ubuntu-24.04
    steps:
      - name: local-step
        run: |
          echo "Local step"
          echo ${{ secrets.TEST_SECRET }}

