name: test

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["master", "main"]
jobs:
  testjob:
    name: Test Job
    if: (github.actor != 'dependabot[bot]')
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    env:
      SEMGREP_APP_URL: "testurl"
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          echo "hello"
