name: Local Job

on:
  workflow_dispatch: {}
  pull_request: {}
  pull_request_target: {}
  push:
    branches:
      - '**'

jobs:
  local-job:
    runs-on: ubuntu-24.04
    steps:
      - name: local-step
        run: |
          echo "Local step"



