name: SecureSDLC2

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master

jobs:
  securesdlc:
    runs-on: ubuntu-24.04
    steps:
      - name: test
        run: |
          pwd


